/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.7.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    // appropriate javafx plugin
    alias(libs.plugins.javafx) 
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// javafx configuration block
javafx { 
	version = libs.versions.javafxv.get()
	modules = listOf("javafx.controls", "javafx.graphics") 
} 

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.MyPicture"
}

